version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - "nginx-proxy"
    networks:
      - net
    environment:
      - DEFAULT_EMAIL=${DEFAULT_SSL_EMAIL}

  php:
    build: ./php
    container_name: php
    environment:
      - PHP_MEMORY_LIMIT=128M
    ports:
      - "9000:9000"
    networks:
      - php-internal
    volumes:
      - ../../apps/picocms/html:/usr/share/nginx/picocms/html
      - ../../apps/standardnotes/html:/usr/share/nginx/standardnotes/html
      - ${PICO_DATA_DIR:-../../apps/picocms/html}:/usr/share/nginx/picocms/html

  pico-cms:
    image: nginx
    container_name: ${DOMAIN}
    volumes:
      - ../../apps/picocms/:/usr/share/nginx/picocms/
      - ../../apps/picocms/conf.d:/etc/nginx/conf.d
      - ${PICO_DATA_DIR:-../../apps/picocms/html}:/usr/share/nginx/picocms/html
    networks:
      - php-internal
      - net
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=${DOMAIN},www.${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN},www.${DOMAIN}
 
#  standard-notes:
#    image: nginx
#    container_name: notes.${DOMAIN}
#    volumes:
#      - ./notes.${DOMAIN}/html:/usr/share/nginx/notes.${DOMAIN}/html
#      - ./notes.${DOMAIN}/conf.d:/etc/nginx/conf.d
#    networks:
#      - "net"
#    environment:
#      - VIRTUAL_HOST=notes.${DOMAIN}
#      - LETSENCRYPT_HOST=notes.${DOMAIN}

#  (working)
#  homer-dashboard:
#    image: b4bz/homer
#    container_name: apps.${DOMAIN}
#    volumes:
#      - ${HOMER_DATA_DIR:-../../apps/homer-dashboard/public/assets}:/www/assets
#    ports:
#      - 8080:8080
#    networks:
#      - "net"
#    environment:
#      - VIRTUAL_HOST=apps.${DOMAIN}
#      - LETSENCRYPT_HOST=apps.${DOMAIN}

#  (working)
#  kanboard:
#    image: kanboard/kanboard:latest
#    container_name: kanboard
#    depends_on:
#      - "acme-companion"
#    environment:
#      - VIRTUAL_HOST=tasks.${DOMAIN}
#      - LETSENCRYPT_HOST=tasks.${DOMAIN}  
#    networks:
#      - "net"
#    ports:
#      - "8083:80"
#      - "8084:443"
#    volumes:
#      - ../../apps/kanboard/data:/var/www/app/data
#      - ../../apps/kanboard/plugins:/var/www/app/plugins

#  (working)
#  dokuwiki:
#    image: linuxserver/dokuwiki:version-2020-07-29
#    container_name: dokuwiki
#    restart: unless-stopped
#    volumes:
#      - ../../apps/dokuwiki/config:/config
#      - ${DOKUWIKI_CONF_DIR:-../../apps/dokuwiki/config/dokuwiki/conf}:/config/dokuwiki/conf
#      - ${DOKUWIKI_DATA_DIR:-../../apps/dokuwiki/config/dokuwiki/data}:/config/dokuwiki/data
#    ports:
#      - 8085:443/tcp
#      - 8086:80/tcp
#    environment:
#      - VIRTUAL_HOST=wiki.${DOMAIN}
#      - LETSENCRYPT_HOST=wiki.${DOMAIN}  
#    networks:
#      - "net"    

#    environment:
#      - VIRTUAL_HOST=tasks.${DOMAIN}
#      - LETSENCRYPT_HOST=tasks.${DOMAIN}    nextcloud-app:

#  db:
#    image: mariadb
#    container_name: db
#    restart: always
#    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed 
#    volumes:
#      - db:/var/lib/mysql
#    networks:
#      - net

  nextcloud-app:
    image: nextcloud:fpm
    container_name: nextcloud-app
    restart: always
    volumes:
      - nc:/var/www/html
    networks:
      - cloud-internal

  nextcloud-web:
    image: nginx
    container_name: nextcloud-web
    restart: always
    ports:
      - 8087:80
    networks:
      - net
      - cloud-internal
    environment:
      - VIRTUAL_HOST=cloud.${DOMAIN}
      - LETSENCRYPT_HOST=cloud.${DOMAIN}
    volumes:
      - nc:/var/www/html:ro
      - ../../apps/nextcloud/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud-app


volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  db:
  nc:

networks:
  net:  
    driver: bridge
  cloud-internal:
    driver: bridge
  php-internal:
    driver: bridge
